Repository pyswmm/pyswmm, pull requests merged in 2019-07, with the labels that each got.

#191 Eliminating VCOMP DLL Not Found on Windows
  pyswmm/lib/__init__.py
  pyswmm/lib/windows/vcomp120.dll
Labels: reso:completed, type:bug

#152 LID Support
  .travis.yml
  appveyor.yml
  pyswmm/__init__.py
  pyswmm/lib/__init__.py
  pyswmm/lib/linux/swmm5.so
  pyswmm/lib/macos/swmm5.dylib
  pyswmm/lib/macos/swmm5.so
  pyswmm/lib/windows/swmm5-x64.dll
  pyswmm/lib/windows/swmm5.dll
  pyswmm/lib/windows/vcomp120.dll
  pyswmm/lidcontrols.py
  pyswmm/lidgroups.py
  pyswmm/lidlayers.py
  pyswmm/lidunits.py
  pyswmm/swmm5.py
  pyswmm/tests/data/__init__.py
  pyswmm/tests/data/model_bad_input_1.inp
  pyswmm/tests/data/model_lids.inp
  pyswmm/tests/test_errors.py
  pyswmm/tests/test_general_engine.py
  pyswmm/tests/test_import.py
  pyswmm/tests/test_lid.py
  pyswmm/tests/test_nodes.py
  pyswmm/tests/test_pollutants.py
  pyswmm/toolkitapi.py
  setup.py
Labels: type:enhancement, type:feature

#198 Merging Abhi's Raingage API work
  pyswmm/__init__.py
  pyswmm/raingages.py
  pyswmm/swmm5.py
  pyswmm/tests/data/__init__.py
  pyswmm/tests/data/model_rain.inp
  pyswmm/tests/test_rainfallAPI.py
  pyswmm/toolkitapi.py
Labels: type:enhancement, type:feature

#204 Bug Fix Issue 164
  pyswmm/swmm5.py
Labels: reso:completed, type:bug

#203 Merge develop to master
  .travis.yml
  appveyor.yml
  docs/source/authors.rst
  docs/source/install.rst
  docs/source/reference/index.rst
  docs/source/reference/lidcontrols.rst
  docs/source/reference/lidgroups.rst
  docs/source/reference/lidlayers.rst
  docs/source/reference/lidunits.rst
  docs/source/reference/raingages.rst
  docs/source/tutorial/tutorial.rst
  pyswmm/__init__.py
  pyswmm/lib/__init__.py
  pyswmm/lib/linux/swmm5.so
  pyswmm/lib/macos/swmm5.dylib
  pyswmm/lib/macos/swmm5.so
  pyswmm/lib/windows/swmm5-x64.dll
  pyswmm/lib/windows/swmm5.dll
  pyswmm/lib/windows/vcomp120.dll
  pyswmm/lidcontrols.py
  pyswmm/lidgroups.py
  pyswmm/lidlayers.py
  pyswmm/lidunits.py
  pyswmm/raingages.py
  pyswmm/swmm5.py
  pyswmm/tests/data/__init__.py
  pyswmm/tests/data/model_bad_input_1.inp
  pyswmm/tests/data/model_lids.inp
  pyswmm/tests/data/model_rain.inp
  pyswmm/tests/test_errors.py
  pyswmm/tests/test_general_engine.py
  pyswmm/tests/test_import.py
  pyswmm/tests/test_lid.py
  pyswmm/tests/test_links.py
  pyswmm/tests/test_nodes.py
  pyswmm/tests/test_rainfallAPI.py
  pyswmm/tests/test_subcatchments.py
  pyswmm/tests/test_system.py
  pyswmm/toolkitapi.py
  setup.py
Labels: reso:completed
